// Generated by carbonsteel. DO NOT EDIT. Source: openapi.yaml#/paths (tag: account)

import { APIResource } from '../resource';
import * as Core from '../core';

export class Accounts extends APIResource {
  /**
   * Returns details about your account.
   */
  retrieve(options?: Core.RequestOptions): Core.APIPromise<AccountRetrieveResponse> {
    return this._client.get('/v1/account', options);
  }
}

export interface AccountRetrieveResponse {
  plan: AccountRetrieveResponse.Plan;

  usage: AccountRetrieveResponse.Usage;
}

export namespace AccountRetrieveResponse {
  export interface Plan {
    /**
     * The maximum number of characters per billing period allowed by your plan.
     */
    character_limit: number;

    commercial_use_allowed: boolean;

    /**
     * The type of plan you are subscribed to.
     */
    type: string;
  }

  export interface Usage {
    /**
     * The number of characters remaining in this billing period.
     */
    characters: number;
  }
}

export declare namespace Accounts {
  export { type AccountRetrieveResponse as AccountRetrieveResponse };
}
