// Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/operations (initMessage)

import { Buffer } from 'buffer';
import { APIResource } from '../resource';
import { WebSocket } from '../_shims/index';
import { LMNT_API_VERSION } from '../version';
import {
  MessageQueue,
  WEBSOCKET_NORMAL_CLOSE,
  WEBSOCKET_OPEN_STATE,
  processAudioData,
} from '../_websocketRuntime';

const URL_STREAMING = 'wss://api.lmnt.com/v1/ai/speech/stream';

export interface Timestamp {
  /**
   * The text segment
   */
  text: string;

  /**
   * The time at which the text starts, in seconds
   */
  start: number;

  /**
   * The spoken duration of the text segment, in seconds
   */
  duration: number;
}

export type SpeechStreamMessage = AudioMessage | ExtrasMessage | ErrorMessage | CompleteMessage;

/**
 * Audio message containing synthesized speech data
 */
export interface AudioMessage {
  type: 'audio';
  audio: ArrayBuffer | Buffer;
}

/**
 * Extras message containing metadata about the synthesis
 */
export interface ExtrasMessage {
  type: 'extras';
  timestamps?: Array<Timestamp>;
  buffer_empty?: boolean;
  warning?: string;
}

/**
 * Error message containing error information
 */
export interface ErrorMessage {
  type: 'error';
  error: string;
}

/**
 * Complete message for commands (reset/flush)
 */
export interface CompleteMessage {
  type: 'complete';
  complete: 'reset' | 'flush';
  nonce: number;
}

export class SpeechSession {
  private socket: WebSocket;
  private outMessages: any[] = [];
  private inMessages: MessageQueue;
  private returnExtras: boolean;
  private nextNonce: number = 1;

  /**
   * Creates a new streaming speech connection.
   * @param apiKey The API key to use for the connection. Obtain a key
   *     from the [LMNT account page](https://app.lmnt.com/account).
   * @param options Configuration options including voice, format, language,
   *     sample rate, and other synthesis parameters.
   */
  constructor(apiKey: string, options: SpeechSessionParams) {
    this.outMessages = [];
    this.inMessages = new MessageQueue();
    this.returnExtras = options.return_extras || false;

    this.socket = new WebSocket(URL_STREAMING);
    this.setupWebSocket();

    this.sendMessage({
      'X-API-Key': apiKey,
      'lmnt-version': LMNT_API_VERSION,
      voice: options.voice,
      format: options.format,
      language: options.language,
      return_extras: options.return_extras,
      sample_rate: options.sample_rate,
    });
  }

  private setupWebSocket() {
    this.socket.onerror = this.onError.bind(this);
    this.socket.onmessage = this.onMessage.bind(this);
    this.socket.onopen = this.onOpen.bind(this);
    this.socket.onclose = this.onClose.bind(this);
  }

  private onError(event: any) {
    console.error('WebSocket error:', event);
    this.inMessages.finish();
  }

  private onOpen() {
    this.flushMessages();
  }

  private onClose(event: any) {
    if (event.code !== WEBSOCKET_NORMAL_CLOSE) {
      console.warn(`WebSocket closed unexpectedly with code: ${event.code}, reason: ${event.reason}`);
    }
    this.socket = null as any;
    this.inMessages.finish();
  }

  private onMessage(event: MessageEvent) {
    const isText = typeof event.data === 'string';
    this.inMessages.push({
      type: isText ? 'text' : 'binary',
      data: event.data,
    });
  }

  /**
   * Appends text to the overall text to be synthesized.
   * @param text The additional text to synthesize.
   */
  appendText(text: string) {
    this.sendMessage({ text: text });
  }

  /**
   * Releases resources associated with this instance and closes the WebSocket connection.
   */
  close() {
    if (this.socket) {
      this.socket.close();
      this.socket = null as any;
    }
  }

  /**
   * Triggers the server to synthesize all currently queued text and return the audio data.
   * Use sparingly as it may affect the natural flow of speech synthesis.
   *
   * @returns The nonce used for this flush command
   */
  flush(): number {
    const nonce = this.nextNonce++;
    this.sendMessage({ command: 'flush', nonce });
    return nonce;
  }

  /**
   * Resets the speech session, discarding all queued text and stopping current synthesis.
   *
   * @returns The nonce used for this reset command
   */
  reset(): number {
    const nonce = this.nextNonce++;
    this.sendMessage({ command: 'reset', nonce });
    return nonce;
  }

  /**
   * Finishes the streaming session after writing all text. This will flush remaining data
   * and close the connection after all audio has been received.
   */
  finish() {
    this.sendMessage({ command: 'eof' });
  }

  /**
   * Iterate over messages from the server.
   *
   * @returns AsyncIterator<SpeechStreamMessage>
   */
  async *[Symbol.asyncIterator](): AsyncIterator<SpeechStreamMessage> {
    while (true) {
      const message = await this.inMessages.next();
      if (message === null) {
        return;
      }

      if (message.type === 'text') {
        yield this.parseTextMessage(message.data);
      } else {
        try {
          const audio = await processAudioData(message.data);
          yield { type: 'audio', audio };
        } catch (error) {
          yield { type: 'error', error: error instanceof Error ? error.message : String(error) };
        }
      }
    }
  }

  private parseTextMessage(textData: string): SpeechStreamMessage {
    const messageJson = JSON.parse(textData);

    if ('error' in messageJson) {
      return { type: 'error', ...messageJson };
    }

    if ('complete' in messageJson) {
      return { type: 'complete', ...messageJson };
    }

    if (
      this.returnExtras &&
      (messageJson.timestamps || messageJson.warning || messageJson.buffer_empty !== undefined)
    ) {
      return { type: 'extras', ...messageJson };
    }

    return { type: 'error', ...messageJson };
  }

  private sendMessage(message: any) {
    this.outMessages.push(message);
    this.flushMessages();
  }

  private flushMessages() {
    if (this.socket?.readyState === WEBSOCKET_OPEN_STATE) {
      while (this.outMessages.length) {
        const message = this.outMessages.shift();
        this.socket.send(JSON.stringify(message));
      }
    }
  }
}

export class Sessions extends APIResource {
  /**
   * Stream text to our servers and receive generated speech in real-time. Great for latency-sensitive applications and situations where you don't have all the text upfront.
   */
  create(body: SpeechSessionParams) {
    return new SpeechSession(this._client.apiKey, body);
  }
}

export interface SpeechSessionParams {
  /**
   * The voice ID to use for speech generation, obtained from 'List voices' API
   */
  voice: string;

  /**
   * The desired output format of the audio.
   * - `mp3`: 96kbps MP3 audio.
   * - `pcm_s16le`: PCM signed 16-bit little-endian audio.
   * - `pcm_f32le`: PCM 32-bit floating-point little-endian audio.
   * - `ulaw`: 8-bit G711 µ-law audio with a WAV header.
   * - `webm`: WebM format with Opus audio codec.
   */
  format?: 'mp3' | 'pcm_s16le' | 'pcm_f32le' | 'ulaw' | 'webm';

  /**
   * The desired language. Two letter ISO 639-1 code. Defaults to auto language detection.
   */
  language?:
    | 'auto'
    | 'ar'
    | 'as'
    | 'bn'
    | 'cs'
    | 'da'
    | 'de'
    | 'en'
    | 'es'
    | 'fi'
    | 'fr'
    | 'hi'
    | 'id'
    | 'it'
    | 'ja'
    | 'ko'
    | 'ml'
    | 'mr'
    | 'nl'
    | 'pl'
    | 'pt'
    | 'ru'
    | 'sk'
    | 'sv'
    | 'ta'
    | 'te'
    | 'th'
    | 'tr'
    | 'uk'
    | 'ur'
    | 'vi'
    | 'zh';

  /**
   * Controls whether the server will return extra information about the generated speech
   */
  return_extras?: boolean;

  /**
   * The desired output audio sample rate
   */
  sample_rate?: 24000 | 16000 | 8000;
}

export declare namespace Sessions {
  export { type SpeechSessionParams as SpeechSessionParams };
  export { SpeechSession as SpeechSession };
}
