// Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/operations (initMessage)

import { APIResource } from '../resource';
import { SpeechSession } from '../lib/websocketStreaming';

export class Sessions extends APIResource {
  /**
   * Stream text to our servers and receive synthesized speech in real-time. Great for latency-sensitive applications and situations where you don't have all the text upfront.
   */
  create(body: SpeechSessionParams) {
    return new SpeechSession(this._client.apiKey, body);
  }
}

export interface SpeechSessionParams {
  /**
   * The voice ID to use for synthesis, obtained from 'List voices' API
   */
  voice: string;

  /**
   * The desired output format of the audio.
   * - `mp3`: 96kbps MP3 audio.
   * - `pcm_s16le`: PCM signed 16-bit little-endian audio.
   * - `pcm_f32le`: PCM 32-bit floating-point little-endian audio.
   * - `ulaw`: 8-bit G711 µ-law audio with a WAV header.
   * - `webm`: WebM format with Opus audio codec.
   */
  format?: 'mp3' | 'pcm_s16le' | 'pcm_f32le' | 'ulaw' | 'webm';

  /**
   * The desired language. Two letter ISO 639-1 code. Defaults to auto language detection.
   */
  language?:
    | 'auto'
    | 'ar'
    | 'de'
    | 'en'
    | 'es'
    | 'fr'
    | 'hi'
    | 'id'
    | 'it'
    | 'ja'
    | 'ko'
    | 'nl'
    | 'pl'
    | 'pt'
    | 'ru'
    | 'sv'
    | 'th'
    | 'tr'
    | 'uk'
    | 'ur'
    | 'vi'
    | 'zh';

  /**
   * Controls whether the server will return extra information about the synthesis
   */
  return_extras?: boolean;

  /**
   * The desired output audio sample rate
   */
  sample_rate?: 24000 | 16000 | 8000;
}

export declare namespace Sessions {
  export { type SpeechSessionParams as SpeechSessionParams };
  export { SpeechSession as SpeechSession };
}
