configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lmnt-kaikato-aryp6r%2Flmnt-com-2e3329041b9931ca67c7cc9be955f5e6827a931a70e136d705d59f201b3672a1.yml
