configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lmnt-kaikato-aryp6r%2Flmnt-com-bd4e60fe69b130d9714dfd09dffed464245dd9ae5e7c93cca2e39a2e5cd2ad7e.yml
openapi_spec_hash: b1e55f9426fdde4b45ac0963dd0958fa
config_hash: 09b5484ce79cbec6d92262e8f9bee55c
