configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lmnt-kaikato-aryp6r%2Flmnt-com-c4f3900d3b2865814e693aa7cacb1637c31c90146c58f6e35ee79d92a3bec82d.yml
