configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lmnt-kaikato-aryp6r%2Flmnt-com-2f5b23b6daac3a27930ab121f14a9e8fd327cd4ed22cde5f4f7c9bc33fd7b7ff.yml
