configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lmnt-kaikato-aryp6r%2Flmnt-com-d1b59768dd6e04b4b8226ed0b9a0bc243949555852e94cc92f8168e634a5509c.yml
