configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lmnt-kaikato-aryp6r%2Flmnt-com-fe093ba357c5d4379ec75eff308cf9bdffa9cce4f9cc40dff594a64adf71084d.yml
