configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lmnt-kaikato-aryp6r%2Flmnt-com-d7b1e6d66ece86ca2b84deb6f8b001016f3eb0f49a3ae8751e54d6c7b79d2a25.yml
