configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lmnt-kaikato-aryp6r%2Flmnt-com-b404cfde6be04e03b7b0d65002642cbc4d472aa7964f0cec237738d587c793ce.yml
