configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lmnt-kaikato-aryp6r%2Flmnt-com-49723c4435f19fc54ba4a1bf6f2efb48661c9bf3b339ec40637f3fa58ace462d.yml
