configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lmnt-kaikato-aryp6r%2Flmnt-com-d28205275ec46c0eada0ab29a7568bb6a08bbac82ddb1f286aa8b7f6e9ac0659.yml
