// Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/operations

import Lmnt from 'lmnt-node';

jest.mock('../../src/_shims/index', () => {
  class FakeWebSocket {
    static instances: any[] = [];
    onerror: any = null;
    onmessage: any = null;
    onopen: any = null;
    onclose: any = null;
    readyState = 0;
    sent: string[] = [];

    constructor(_url: string) {
      FakeWebSocket.instances.push(this);
    }
    send(message: string) {
      this.sent.push(message);
    }
    close() {
      this.onclose?.({ code: 1000 });
    }

    simulateOpen() {
      this.readyState = 1;
      this.onopen?.();
    }
    simulateMessage(data: any) {
      this.onmessage?.({ data });
    }
    simulateClose(event: { code: number }) {
      this.onclose?.(event);
    }
  }
  return { ...jest.requireActual('../../src/_shims/index'), WebSocket: FakeWebSocket };
});

import { WebSocket as _WebSocket } from '../../src/_shims/index';
const FakeWebSocket = _WebSocket as any;

const client = new Lmnt({
  apiKey: 'test-api-key',
});

describe('resource sessions', () => {
  beforeEach(() => {
    FakeWebSocket.instances = [];
  });

  test('initMessageOperation', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id' });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    // First sent frame is the `initMessage` payload — flushed on socket open.
    expect(fake.sent.length).toBe(1);
    const init = JSON.parse(fake.sent[0]);
    expect(init['X-API-Key']).toBe('test-api-key');
    expect(init['lmnt-version']).toBe('1.1');
    expect(init.voice).toBe('voice-id');
    session.close();
  });

  test('textStreamingOperation', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id' });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    session.appendText('hello world');

    expect(fake.sent.length).toBe(2);
    expect(JSON.parse(fake.sent[1])).toEqual({ text: 'hello world' });
    session.close();
  });

  test('flushOperation', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id' });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    const nonce = session.flush();
    expect(nonce).toBe(1);

    expect(fake.sent.length).toBe(2);
    expect(JSON.parse(fake.sent[1])).toEqual({ command: 'flush', nonce: 1 });
    session.close();
  });

  test('eofOperation', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id' });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    session.finish();

    expect(fake.sent.length).toBe(2);
    expect(JSON.parse(fake.sent[1])).toEqual({ command: 'eof' });
    session.close();
  });

  test('receiveAudio', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id' });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    const audioBytes = Buffer.from([0, 1, 2, 3]);
    fake.simulateMessage(audioBytes);
    fake.simulateClose({ code: 1000 });

    const received: any[] = [];
    for await (const msg of session) {
      received.push(msg);
    }

    expect(received.length).toBe(1);
    expect(received[0].type).toBe('audio');
    expect(received[0].audio).toBe(audioBytes);
  });

  test('receiveExtras', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id', return_extras: true });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    const payload = {
      timestamps: [{ text: 'hi', start: 0.0, duration: 0.5 }],
      buffer_empty: true,
      warning: undefined,
    };
    fake.simulateMessage(JSON.stringify(payload));
    fake.simulateClose({ code: 1000 });

    const received: any[] = [];
    for await (const msg of session) {
      received.push(msg);
    }

    expect(received.length).toBe(1);
    expect(received[0].type).toBe('extras');
    expect(received[0].timestamps).toBeDefined();
    expect(received[0].timestamps.length).toBe(1);
    expect(received[0].buffer_empty).toBe(true);
  });

  test('receiveError', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id' });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    fake.simulateMessage(JSON.stringify({ error: 'voice not found' }));
    fake.simulateClose({ code: 1000 });

    const received: any[] = [];
    for await (const msg of session) {
      received.push(msg);
    }

    expect(received.length).toBe(1);
    expect(received[0].type).toBe('error');
    expect(received[0].error).toBe('voice not found');
  });
});
