// Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/operations

import Lmnt from 'lmnt-node';

jest.mock('../../src/_shims/index', () => {
  class FakeWebSocket {
    static instances: any[] = [];
    onerror: any = null;
    onmessage: any = null;
    onopen: any = null;
    onclose: any = null;
    readyState = 0;
    sent: string[] = [];

    constructor(_url: string) {
      FakeWebSocket.instances.push(this);
    }
    send(message: string) {
      this.sent.push(message);
    }
    close() {
      this.onclose?.({ code: 1000 });
    }

    simulateOpen() {
      this.readyState = 1;
      this.onopen?.();
    }
    simulateMessage(data: any) {
      this.onmessage?.({ data });
    }
    simulateClose(event: { code: number }) {
      this.onclose?.(event);
    }
  }
  return { ...jest.requireActual('../../src/_shims/index'), WebSocket: FakeWebSocket };
});

import { WebSocket as _WebSocket } from '../../src/_shims/index';
const FakeWebSocket = _WebSocket as any;

const client = new Lmnt({
  apiKey: 'test-api-key',
});

describe('resource sessions', () => {
  beforeEach(() => {
    FakeWebSocket.instances = [];
  });

  test('initOperation', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id' });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    // First sent frame is the `init` payload — flushed on socket open.
    expect(fake.sent.length).toBe(1);
    const init = JSON.parse(fake.sent[0]);
    expect(init['X-API-Key']).toBe('test-api-key');
    expect(init['lmnt-version']).toBe('1.1');
    expect(init.voice).toBe('voice-id');
    session.close();
  });

  test('textOperation', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id' });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    session.sendText('text-value');

    expect(fake.sent.length).toBe(2);
    expect(JSON.parse(fake.sent[1])).toEqual({ type: 'text', text: 'text-value' });
    session.close();
  });

  test('flushOperation', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id' });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    const nonce = session.sendFlush();
    expect(nonce).toBe(1);

    expect(fake.sent.length).toBe(2);
    expect(JSON.parse(fake.sent[1])).toEqual({ type: 'flush', nonce: 1 });
    session.close();
  });

  test('resetOperation', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id' });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    const nonce = session.sendReset();
    expect(nonce).toBe(1);

    expect(fake.sent.length).toBe(2);
    expect(JSON.parse(fake.sent[1])).toEqual({ type: 'reset', nonce: 1 });
    session.close();
  });

  test('finishOperation', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id' });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    session.sendFinish();

    expect(fake.sent.length).toBe(2);
    expect(JSON.parse(fake.sent[1])).toEqual({ type: 'finish' });
    session.close();
  });

  test('receiveReady', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id' });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    const payload = { type: 'ready', request_id: 'request_id-value' };
    fake.simulateMessage(JSON.stringify(payload));
    fake.simulateClose({ code: 1000 });

    const received: any[] = [];
    for await (const msg of session) {
      received.push(msg);
    }

    expect(received.length).toBe(1);
    expect(received[0].type).toBe('ready');
    expect(received[0].request_id).toBe('request_id-value');
  });

  test('receiveAudio', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id' });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    const payload = Buffer.from([0, 1, 2, 3]);
    fake.simulateMessage(payload);
    fake.simulateClose({ code: 1000 });

    const received: any[] = [];
    for await (const msg of session) {
      received.push(msg);
    }

    expect(received.length).toBe(1);
    expect(received[0].type).toBe('audio');
    expect(received[0].audio).toBe(payload);
  });

  test('receiveTimestamps', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id', return_timestamps: true });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    const payload = { type: 'timestamps', timestamps: [{ text: 'hi', start: 0.0, duration: 0.5 }] };
    fake.simulateMessage(JSON.stringify(payload));
    fake.simulateClose({ code: 1000 });

    const received: any[] = [];
    for await (const msg of session) {
      received.push(msg);
    }

    expect(received.length).toBe(1);
    expect(received[0].type).toBe('timestamps');
    expect(received[0].timestamps).toBeDefined();
    expect(received[0].timestamps.length).toBe(1);
  });

  test('receiveFlushComplete', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id' });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    const payload = { type: 'flush_complete', nonce: 1 };
    fake.simulateMessage(JSON.stringify(payload));
    fake.simulateClose({ code: 1000 });

    const received: any[] = [];
    for await (const msg of session) {
      received.push(msg);
    }

    expect(received.length).toBe(1);
    expect(received[0].type).toBe('flush_complete');
    expect(received[0].nonce).toBe(1);
  });

  test('receiveResetComplete', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id' });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    const payload = { type: 'reset_complete', nonce: 1 };
    fake.simulateMessage(JSON.stringify(payload));
    fake.simulateClose({ code: 1000 });

    const received: any[] = [];
    for await (const msg of session) {
      received.push(msg);
    }

    expect(received.length).toBe(1);
    expect(received[0].type).toBe('reset_complete');
    expect(received[0].nonce).toBe(1);
  });

  test('receiveError', async () => {
    const session = client.speech.sessions.create({ voice: 'voice-id' });
    const fake = FakeWebSocket.instances[0];
    fake.simulateOpen();

    const payload = { type: 'error', error: undefined, request_id: 'request_id-value' };
    fake.simulateMessage(JSON.stringify(payload));
    fake.simulateClose({ code: 1000 });

    const received: any[] = [];
    for await (const msg of session) {
      received.push(msg);
    }

    expect(received.length).toBe(1);
    expect(received[0].type).toBe('error');
    expect(received[0].request_id).toBe('request_id-value');
  });
});
