// Generated by carbonsteel. DO NOT EDIT. Source: openapi.yaml#/paths (tag: speech)

import Lmnt from 'lmnt-node';
import { Response } from 'node-fetch';

const client = new Lmnt({
  apiKey: 'My API Key',
  baseURL: process.env['TEST_API_BASE_URL'] ?? 'http://127.0.0.1:4010',
});

describe('resource speech', () => {
  test('generate: required and optional params', async () => {
    const response = await client.speech.generate({
      text: "Uhh, did you see the weather in Palo Alto tomorrow? Yeah, can't believe it's gonna rain, dude. Like what?",
      voice: 'leah',
      debug: true,
      format: 'aac',
      language: 'auto',
      model: 'blizzard',
      sample_rate: 8000,
      temperature: 0,
      top_p: 0,
    });
  });

  test('generateDetailed: only required params', async () => {
    const responsePromise = client.speech.generateDetailed({
      text: "Uhh, did you see the weather in Palo Alto tomorrow? Yeah, can't believe it's gonna rain, dude. Like what?",
      voice: 'leah',
    });
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  test('generateDetailed: required and optional params', async () => {
    const response = await client.speech.generateDetailed({
      text: "Uhh, did you see the weather in Palo Alto tomorrow? Yeah, can't believe it's gonna rain, dude. Like what?",
      voice: 'leah',
      debug: true,
      format: 'aac',
      language: 'auto',
      model: 'blizzard',
      return_timestamps: true,
      sample_rate: 8000,
      temperature: 0,
      top_p: 0,
    });
  });
});
