// Generated by carbonsteel. DO NOT EDIT.

import type { Lmnt } from './index';

export abstract class APIResource {
  protected _client: Lmnt;

  constructor(client: Lmnt) {
    this._client = client;
  }
}
